services:
  accounts:
    image: "tutkuince/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
  loans:
    image: "tutkuince/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
  cards:
    image: "tutkuince/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
networks:
  easybank:
    driver: bridge

# to run this file: "docker compose up -d"
# to stop and remove all containers: "docker compose down"