services:
  accountsDB:
    container_name: accountsDB
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsDB
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsDB:
    container_name: cardsDB
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cardsDB
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansDB:
    container_name: loansDB
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: loansDB
    extends:
      file: common-config.yml
      service: microservice-db-config

  config-server:
    image: tutkuince/config-server:0.0.4-SNAPSHOT
    container_name: config-server
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eureka-server:
    image: tutkuince/eureka-server:0.0.2-SNAPSHOT
    container_name: eureka-server
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eureka-server"

  account-service:
    image: tutkuince/account-service:0.0.4-SNAPSHOT
    container_name: account-service
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      config-server:
        condition: service_healthy
      accountsDB:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "account-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsDB:3306/accountsDB"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  card-service:
    image: tutkuince/card-service:0.0.4-SNAPSHOT
    container_name: card-service
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      config-server:
        condition: service_healthy
      cardsDB:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "card-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsDB:3306/cardsDB"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans-service:
    image: tutkuince/loans-service:0.0.4-SNAPSHOT
    container_name: loans-service
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      config-server:
        condition: service_healthy
      loansDB:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansDB:3306/loansDB"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gateway-server:
    image: tutkuince/gateway-server:0.0.1-SNAPSHOT
    container_name: gateway-server
    ports:
      - "8072:8072"
    depends_on:
      account-service:
        condition: service_healthy
      card-service:
        condition: service_healthy
      loans-service:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gateway-server"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  easybank:
    driver: bridge