services:
  accountsDB:
    container_name: accountsDB
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsDB
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsDB:
    container_name: cardsDB
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cardsDB
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansDB:
    container_name: loansDB
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: loansDB
    extends:
      file: common-config.yml
      service: microservice-db-config

  config-server:
    image: tutkuince/config-server:0.0.2-SNAPSHOT
    container_name: config-server
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  account-service:
    image: tutkuince/account-service:0.0.2-SNAPSHOT
    container_name: account-service
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      accountsDB:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "account-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsDB:3306/accountsDB"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  card-service:
    image: tutkuince/card-service:0.0.2-SNAPSHOT
    container_name: card-service
    ports:
      - "9000:9000"
    depends_on:
      config-server:
        condition: service_healthy
      cardsDB:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "card-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsDB:3307/cardsDB"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loan-service:
    image: tutkuince/loans-service:0.0.2-SNAPSHOT
    container_name: loan-service
    ports:
      - "8090:8090"
    depends_on:
      config-server:
        condition: service_healthy
      loansDB:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loan-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansDB:3308/loansDB"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  easybank:
    driver: bridge