services:
  configserver:
    image: "tutkuince/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
  accounts:
    image: "tutkuince/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
  loans:
    image: "tutkuince/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
  cards:
    image: "tutkuince/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
networks:
  easybank:
    driver: bridge

# we need to run that commands in the same path with docker-compose.yml file.
# to run this file:                   "docker compose up -d"
# to stop and remove all containers:  "docker compose down"

# to just stop all containers:    "docker compose stop"
# to run that stopped containers: "docker compose start"