services:
  rabbit:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  config-server:
    image: tutkuince/config-server:0.0.1-SNAPSHOT
    container_name: config-server
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  account-service:
    image: tutkuince/account-service:0.0.1-SNAPSHOT
    container_name: account-service
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "account-service"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loan-service:
    image: tutkuince/loans-service:0.0.1-SNAPSHOT
    container_name: loan-service
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loan-service"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  card-service:
    image: tutkuince/card-service:0.0.1-SNAPSHOT
    container_name: card-service
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "card-service"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  easybank:
    driver: bridge