services:
  accountsdb:
    image: mariadb
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    image: mariadb
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MARIADB_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    image: mariadb
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MARIADB_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "tutkuince/configserver:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "tutkuince/accounts:s7"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mariadb://accountsdb:3306/accountsdb"
    depends_on:
      accountsdb:
        condition: service_healthy

    extends:
      file: common-config.yml
      service: microservice-configserver-config


  loans:
    image: "tutkuince/loans:s7"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mariadb://loansdb:3307/loansdb"
    depends_on:
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "tutkuince/cards:s7"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mariadb://cardsdb:3308/cardsdb"
    depends_on:
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  easybank:
    driver: bridge

# we need to run that commands in the same path with docker-compose.yml file.
# to run this file:                   "docker compose up -d"
# to stop and remove all containers:  "docker compose down"

# to just stop all containers:    "docker compose stop"
# to run that stopped containers: "docker compose start"