server:
  port: 8080

spring:
  profiles:
    active: "qa"

  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"

  datasource:
    url: jdbc:h2:mem:accountDB
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

build:
  version: "3.0"

account-service:
  message: "Welcome to EasyBank account related local APIs"
  contact-details:
    name: "Tutku Ince - Developer"
    email: "tince@mail.com"
  on-call-support:
    - (555) 555-5555
    - (555) 556-5656