server:
  port: 8071

spring:
  application:
    name: "config-server"

  profiles:
    active: git
  # active: native -> we should activate only when you are using the approaches like classpath, location and file system.

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/tutkuince/easy-bank-configserver.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "classpath:/config"

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"