spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

account-service:
  message: "Welcome to EasyBank card related prod APIs"
  contact-details:
    name: "Çiko Ince - Product Owner"
    email: "cince@mail.com"
  on-call-support:
    - (111) 111-1111
    - (111) 116-1616